"""Added smile_today, drained_today, grateful_today

Revision ID: fa1b3f9fa642
Revises: 
Create Date: 2025-07-31 15:41:38.693926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1b3f9fa642'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reflection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smile_today', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('drained_today', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('grateful_today', sa.Text(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reflection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_column('grateful_today')
        batch_op.drop_column('drained_today')
        batch_op.drop_column('smile_today')

    # ### end Alembic commands ###
